### PR TITLE
Added implementation for Optional Meeting Attendees and required tests.

### PR DESCRIPTION
**Pull request by cheoalee**
Passed all given and additionally required test, added fix for NullPointerException due to getOptionalAttendees() (because of faulty MeetingRequest initialization).

### CODE REVIEW

**Comment by vidhyal** [comment]
Please resolve conflicts.

**Comment by vidhyal** [comment]
Can you please rebase on master. This PR seems to include older commits too.

**Comment by cheoalee** [comment]
> Can you please rebase on master. This PR seems to include older commits too.

I'm holding off on this because master is not even up to date with the non-week 5 material, and I don't want to rebase to a head that won't even be the end head. Perhaps my understanding of rebase is wrong, but it basically appends this on; I'd rather it append on to the fully updated version. Also, I'm going to merge this PR last.

**Comment by vidhyal** [comment]
Please resolve conflicts.

**Comment by cheoalee** [comment]
> Please resolve conflicts.

Done! Thanks for the note.

**Pull request merged**
